# Generated by Django 6.0 on 2026-01-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapper', '0002_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedSwaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('slot_id', models.IntegerField()),
                ('swap_slot_id', models.IntegerField()),
            ],
        ),
    ]
