# Generated by Django 6.0 on 2026-01-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapper', '0003_requestedswaps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestedSwaps',
        ),
        migrations.AddField(
            model_name='slots',
            name='request_swap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slots',
            name='swap_with',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
